name: sid_lsg
channels:
  - defaults
dependencies:
  - python=3.11.9=h955ad1f_0
  - pip:
    - accelerate==0.30.0
    - bitsandbytes==0.43.1
    - blobfile==2.1.1
    - click==8.1.7
    - datasets==2.19.0
    - diffusers==0.27.2
    - dill==0.3.8
    - ftfy==6.2.0
    - huggingface-hub==0.23.0
    - jinja2==3.1.3
    - numpy==1.26.4
    - open-clip-torch==2.24.0
    - peft==0.10.0
    - pillow==10.3.0
    - pip==23.3.1
    - requests==2.31.0
    - safetensors==0.4.3
    - scipy==1.13.0
    - six==1.16.0
    - timm==0.9.16
    - tokenizers==0.19.1
    - torch==2.3.0
    - torchvision==0.18.0
    - tqdm==4.66.4
    - transformers==4.40.1
    - xformers==0.0.26.post1
